[[initializr-documentation]]
= Spring Initializr Documentation

[partintro]
--
This section provides a brief overview of Spring Initializr reference documentation. Think
of it as map for the rest of the document. Some sections are targeted to a specific
audience so this reference guide is not meant to be read in a linear fashion.
--

Spring Initializr provides an extensible API to generate quickstart projects. Such an API
can be used standalone or embedded in other tools. We also provide a configurable service:
you can see our default instance at https://start.spring.io. It provides a simple web UI
to configure the project to generate and endpoints that you can use via plain HTTP.

The service allows you to customize the project to generate: the build system and its
coordinates, the language and version, the packaging and finally the dependencies to add
the project. The latter is a core concept: based on the chosen Spring Boot version, a set
of dependencies can be chosen, usually Spring Boot starters, that will have a concrete
impact on your application. More details in the <<user-guide.adoc#user-guide>>.

You can easily create your own instance: there is minimal code involved and the service
has a very rich configuration structure, allowing you to define not only the values of
various project attributes but also the list of dependencies and the constraints to apply
to them.

Spring Initializr also exposes an endpoint that serves its metadata in a well-known format
to allow third-party clients to provide the necessary assistance. Currently, all the major
Java IDEs are covered and you can generate a project right from your favourite IDE.


[[initializr-documentation-about]]
== About the documentation
The Spring Initializr reference guide is available as
{spring-initializr-docs}/html[html],
{spring-initializr-docs}/pdf/spring-boot-reference.pdf[pdf]
and {spring-initializr-docs}/epub/spring-boot-reference.epub[epub] documents. The
latest copy is available at {spring-initializr-docs-current}.

Copies of this document may be made for your own use and for
distribution to others, provided that you do not charge any fee for such copies and
further provided that each copy contains this Copyright Notice, whether distributed
in print or electronically.



[[initializr-documentation-getting-help]]
== Getting help
Having trouble with Spring Initializr, We'd like to help!

* Ask a question on https://gitter.im/spring-io/initializr[Gitter].
* Report bugs with Spring Initializr at https://github.com/spring-io/initializr/issues.

NOTE: All of Spring Initializr is open source, including the documentation! If you
find problems with the docs; or if you just want to improve them, please
{github-code}[get involved].