github-repo: "https://github.com/spring-io/initializr.git"
github-repo-name: "spring-io/initializr"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
milestone: "0.13.x"
build-name: "initializr"
concourse-url: "https://ci.spring.io"
task-timeout: 30m
registry-mirror-host: docker.repo.spring.io
registry-mirror-username: ((artifactory-username))
registry-mirror-password: ((artifactory-password))