github-repo: "https://github.com/spring-io/initializr.git"
github-repo-name: "spring-io/initializr"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "0.10.x"
milestone: "0.10.x"
build-name: "initializr"
concourse-url: "https://ci.spring.io"
task-timeout: 30m