name: Build Pull Request
on: pull_request

permissions:
  contents: read

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'spring-io/initializr' }}
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version-file: '.sdkmanrc'
          cache: 'maven'

      - name: Set up JDK 17
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: 'maven'
          set-default: false

      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots -Pfull install
